### ISSUE TITLE
More data

### ISSUE THREAD

**Issue by elifoster** [ghuls-apps/ghuls-lib#5]
I think we should get even more data. Currently the data we get is limited. Sure it's interesting, but I think we could go deeper into the User Statistics. 

Here are my current ideas:
- [x] Forks and stargazers: Histogram with each "line" being a repository and the total
- [x] Followers and following: pie chart? Not really sure for this one
- [x] Open issues/PRs, closed issues/PRs/merged PRs: Histogram with each "line" being a repository and the total
- [x] Public, forked, mirrored, private, and total repo count: Pie chart

@Strikingwolf I'd like to know your thoughts.

**Comment by FayeAlephNil** [comment]
If we add by repository we need to add an extra route for the repository name, plus some buttons or something for each repository (web side) in order to access them more easily, all of this is pretty doable, especially web-side, but the design of the cli and web will need to be rethought

**Comment by elifoster** [comment]
Why would we need new routes? It'd be pretty easy to organize it and design it using Google Charts many types of charts. I was thinking we could use histograms for a lot of this data.

The charts that would work for each new set of data I wrote in the main post:
- Forks and stargazers: Histogram with each "line" being a repository and the total
- Followers and following: pie chart? Not really sure for this one
- Commit activity each month: Histogram with each "line" a different month
- Commit activity each year: Histogram with each "line" a different year
- Commit activity average for day of week: Histogram with each "line" a different day of the week (we'd need to decide which format to use for this, because different countries use different day orders)
- Open issues/PRs, closed issues/PRs/merged PRs: Histogram with each "line" being a repository and the total
- Public, forked, mirrored, private, and total repo count: Pie chart

I'd like to know if you have any other ideas for some new data to add. Also take a look at the [Rich Gallery for Google Charts](https://developers.google.com/chart/interactive/docs/gallery), because Chartkick supports it fully, and just looking at the ones available could provide some neat ideas.

**Comment by FayeAlephNil** [comment]
Yes we could display it pretty well that way...I'll take a look at the extra charts to

**Comment by elifoster** [comment]
Closing in favor of other repositories: ghuls-apps/ghuls-web#4, ghuls-apps/ghuls-cli#2, ghuls-apps/github-calendar-api#1

The issue is resolved for the lib, so it doesn't make sense to keep it open here.
