### ISSUE TITLE
Deprecate analyze_user and analyze_orgs

### ISSUE THREAD

**Issue by elifoster** [ghuls-apps/ghuls-lib#7]
@Strikingwolf should we deprecate/delete the analyze methods? They don't really do a whole lot over just running the langs/repos methods. The only difference is that they return nil, which we check with `.nil?`, but that can easily be switched to `.empty?`, as it would do the exact same thing.

**Comment by FayeAlephNil** [comment]
Yep, delete those methods, they have no use and are kinda dumb IMO. There's no point in returning nil and it can actually lead to more errors, not to mention you can just switch to `#empty?`
